firstName = input("first name : ")
middleName = input("middle name : ")
lastName = input("last name : ")
fullName = "{} {} {}".format(firstName, middleName, lastName)
print ("Full Name : ", fullName)
age = int(input("age : "))
branch = input("branch : ")
detail = "{} {} {}".format(fullName, age, branch) 
print("Detail : ", detail) 